from marshmallow import fields
from app.extensions import db
from app.extensions import ma

class Cabecera(db.Model):
    __tablename__ = 'facped'
    __table_args__ = {'schema': 'SiacPracticasa.dbo'}

    ciacodigo       = db.Column(db.String, primary_key=True)
    pednumped       = db.Column(db.String, primary_key=True)
    loccodigo       = db.Column(db.String, primary_key=True)
    facnumfac       = db.Column(db.String  )
    pedtipo         = db.Column(db.String  )
    factippag       = db.Column(db.String  )
    moncodigo       = db.Column(db.String  )
    clicodigo       = db.Column(db.String  )
    garcodigo       = db.Column(db.String  )
    peddirent       = db.Column(db.String  )
    pedcambio       = db.Column(db.Numeric  )
    pedfecemi       = db.Column(db.DateTime )
    pedfecven       = db.Column(db.DateTime )
    pedtivacer      = db.Column(db.Numeric  )
    pedtivapor      = db.Column(db.Numeric  )
    pedsubtot       = db.Column(db.Numeric  )
    pediva          = db.Column(db.Numeric  )
    pedtotal        = db.Column(db.Numeric  )
    pedstatus       = db.Column(db.String  )
    peddetalle      = db.Column(db.String  )
    pedfecisys      = db.Column(db.DateTime )
    pedhorisys      = db.Column(db.DateTime )
    pedusuisys      = db.Column(db.String  )
    pedestisys      = db.Column(db.String  )
    pedfecmsys      = db.Column(db.DateTime )
    pedhormsys      = db.Column(db.DateTime )
    pedusumsys      = db.Column(db.String  )
    pedestmsys      = db.Column(db.String  )
    pedusudes       = db.Column(db.String  )
    vencodigo       = db.Column(db.String  )
    zoncodigo       = db.Column(db.String  )
    pedpordes       = db.Column(db.Numeric  )
    peddesglobal    = db.Column(db.Numeric  )
    peddesdirecto   = db.Column(db.Numeric  )
    pedrecargo      = db.Column(db.Numeric  )
    tipcodigo       = db.Column(db.String  )
    pedporrec       = db.Column(db.Numeric  )
    pedporiva       = db.Column(db.Numeric  )
    pedvalantici    = db.Column(db.Numeric  )
    forintmen       = db.Column(db.Numeric  )
    pedvalinter     = db.Column(db.Numeric  )
    fordias         = db.Column(db.Integer      )
    fortipo         = db.Column(db.String  )
    forcuotas       = db.Column(db.Integer      )
    foraplianti     = db.Column(db.Integer      )
    foranticipo     = db.Column(db.Numeric  )
    foraplirango    = db.Column(db.Integer      )
    formondesde     = db.Column(db.Numeric  )
    formonhasta     = db.Column(db.Numeric  )
    forapligrac     = db.Column(db.Integer      )
    fordiasgrac     = db.Column(db.Integer      )
    forcuoinigr     = db.Column(db.Integer      )
    pedusuanti      = db.Column(db.String  )
    codcodigo       = db.Column(db.String  )
    adinumero       = db.Column(db.String  )
    pednumadi       = db.Column(db.Integer      )
    pedvaladi       = db.Column(db.Numeric  )
    pedapliiva      = db.Column(db.Integer      )
    pedconser       = db.Column(db.Integer      )
    pedlockser      = db.Column(db.String  )
    pedvehi         = db.Column(db.Integer      )
    audnumxml       = db.Column(db.String  )
    integracodigo   = db.Column(db.String  )
    proyectocodigo  = db.Column(db.String  )
    foraprocredito  = db.Column(db.Integer      )
    foraprologistica= db.Column(db.Integer      )
    foraprocliente  = db.Column(db.Integer      )
    pedaprocredito  = db.Column(db.Integer      )
    pedaprologistica= db.Column(db.Integer      )
    pedaprocliente  = db.Column(db.Integer      )
    pedproyecto     = db.Column(db.Integer      )
    pedsolsinstock  = db.Column(db.Integer)
    pedsinstock     = db.Column(db.Integer)
    forpromocion    = db.Column(db.Integer      )
    fordescuento    = db.Column(db.Numeric  )
    regcodigo       = db.Column(db.String  )
    ciucodigo       = db.Column(db.String  )
    procodigo       = db.Column(db.String  )
    pedcierre       = db.Column(db.Integer)
    prosecuen       = db.Column(db.Integer)
    pedusuaped      = db.Column(db.String  )
    pedfecaped      = db.Column(db.DateTime )
    pedhoraped      = db.Column(db.DateTime )
    pedestaped      = db.Column(db.String  )
    pedusuapro      = db.Column(db.String  )
    pedfecapro      = db.Column(db.DateTime )
    pedhorapro      = db.Column(db.DateTime )
    pedestapro      = db.Column(db.String  )
    pedvallincre    = db.Column(db.Numeric  )
    contelef        = db.Column(db.String  )
    transcodigo     = db.Column(db.String  )
    pedforent       = db.Column(db.String  )
    pedcedentrega   = db.Column(db.String  )
    pednomentrega   = db.Column(db.String  )
    nomcontacto     = db.Column(db.String  )
    pedwip          = db.Column(db.String  )
    peddetalle1     = db.Column(db.String  )
    peddetalle2     = db.Column(db.String  )
    peddetalle3     = db.Column(db.String  )

    


    

class CabeceraSchema(ma.SQLAlchemyAutoSchema):
    # pedfecemi  = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecven  = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecisys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhorisys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecmsys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhormsys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecaped = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhoraped = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecapro = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhorapro = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    
    class Meta:
        model = Cabecera