from app.extensions import db
from app.extensions import ma

class Detalle(db.Model):
    __tablename__ = 'fatped'
    __table_args__ = {'schema': 'SiacPracticasa.dbo'}

    ciacodigo       = db.Column(db.String, primary_key=True)
    pednumped       = db.Column(db.String, primary_key=True)
    pedsecuen       = db.Column(db.Integer, primary_key=True)
    loccodigo       = db.Column(db.String, primary_key=True)
    facnumfac       = db.Column(db.String  )
    pedtipo         = db.Column(db.String  )
    pedapliiva      = db.Column(db.Integer     )
    factippag       = db.Column(db.String  )
    moncodigo       = db.Column(db.String  )
    pedcambio       = db.Column(db.Numeric  )
    pedfecemi       = db.Column(db.DateTime )
    clicodigo       = db.Column(db.String  )
    cliprecio       = db.Column(db.Integer     )
    pedstatus       = db.Column(db.String  )
    bodcodigo       = db.Column(db.String  )
    invcodigo       = db.Column(db.String  )
    artcodigo       = db.Column(db.String  )
    precodigo       = db.Column(db.String  )
    coscodigo       = db.Column(db.String  )
    lincodigo       = db.Column(db.String  )
    vencodigo       = db.Column(db.String  )
    zoncodigo       = db.Column(db.String  )
    sercodigo       = db.Column(db.String  )
    pedcantidad     = db.Column(db.Numeric  )
    pedcosto        = db.Column(db.Numeric  )
    pedcostodol     = db.Column(db.Numeric  )
    pedpreven       = db.Column(db.Numeric  )
    pedvaldesglo    = db.Column(db.Numeric  )
    pedvaldesc      = db.Column(db.Numeric  )
    pedvalrec       = db.Column(db.Numeric  )
    pediva          = db.Column(db.Numeric  )
    pedvaliva       = db.Column(db.Numeric  )
    pedvalor        = db.Column(db.Numeric  )
    pedvaltot       = db.Column(db.Numeric  )
    pedfecisys      = db.Column(db.DateTime )
    pedhorisys      = db.Column(db.DateTime )
    pedusuisys      = db.Column(db.String  )
    pedestisys      = db.Column(db.String  )
    pedfecmsys      = db.Column(db.DateTime )
    pedhormsys      = db.Column(db.DateTime )
    pedusumsys      = db.Column(db.String  )
    pedestmsys      = db.Column(db.String  )
    tipcodigo       = db.Column(db.String  )
    pedpordesc      = db.Column(db.Numeric  )
    pedusudesc      = db.Column(db.String  )
    artaplipro      = db.Column(db.Integer     )
    pedvalinter     = db.Column(db.Numeric  )
    medcodigo       = db.Column(db.String  )
    marcodigo       = db.Column(db.String  )
    artpeso         = db.Column(db.Numeric  )
    artserie        = db.Column(db.Integer     )
    artservicio     = db.Column(db.Integer     )
    artexpins       = db.Column(db.Integer     )
    audnumxml       = db.Column(db.String  )
    artfaccero      = db.Column(db.Integer     )
    integracodigo   = db.Column(db.String  )
    proyectocodigo  = db.Column(db.String  )
    pedfecposent    = db.Column(db.DateTime )
    pedcantfacturado= db.Column(db.Numeric  )
    pedpordescori   = db.Column(db.Numeric  )
    pedprecioori    = db.Column(db.Numeric  )
    prosecuen       = db.Column(db.Integer     )
    jefecodigo      = db.Column(db.String  )
    artdescri       = db.Column(db.String  )
    pedusuaped      = db.Column(db.String  )
    pedfecaped      = db.Column(db.DateTime )
    pedhoraped      = db.Column(db.DateTime )
    pedestaped      = db.Column(db.String  )
    pedusuapro      = db.Column(db.String  )
    pedfecapro      = db.Column(db.DateTime )
    pedhorapro      = db.Column(db.DateTime )
    pedestapro      = db.Column(db.String  )

class DetalleSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Detalle