from app.extensions import db
from app.extensions import ma

class Siactloc(db.Model):
    __tablename__ = 'siactloc'
    __table_args__ = {'schema': 'SiacPracticasa.dbo'}
    ciacodigo = db.Column(db.String(2), primary_key=True)
    usrcodigo = db.Column(db.String(10), primary_key=True)
    loccodigo = db.Column(db.String(3), primary_key=True)
    locfecmsys = db.Column(db.DateTime)
    lochormsys = db.Column(db.DateTime)
    locusumsys = db.Column(db.String(10))
    usrflagcaj = db.Column(db.Integer)
    usrcajdesc = db.Column(db.Float)
    usrflagsup = db.Column(db.Integer)
    usrsupdesc = db.Column(db.Float)
    usrflagger = db.Column(db.Integer)
    usrgerdesc = db.Column(db.Float)
    usrmonaprocom = db.Column(db.Float)
    usrflaganuped = db.Column(db.Integer)
    usrflaganufac = db.Column(db.Integer)
    usrflageliant = db.Column(db.Integer)
    usrflagelicob = db.Column(db.Integer)
    usrflagemiped = db.Column(db.Integer)
    usrflagemifac = db.Column(db.Integer)
    usrflagemicob = db.Column(db.Integer)
    usrflagemiab = db.Column(db.Integer)
    usrflagemincd = db.Column(db.Integer)
    usrflagemincm = db.Column(db.Integer)
    usrflagemidg = db.Column(db.Integer)
    usrflagemind = db.Column(db.Integer)
    usrflagemitrainv = db.Column(db.Integer)
    usrflagemicominv = db.Column(db.Integer)
    usrflagemicomser = db.Column(db.Integer)
    usrflagemigasaso = db.Column(db.Integer)
    usrflagemipagpro = db.Column(db.Integer)
    usrflagemipagdir = db.Column(db.Integer)
    usrflagemiantpro = db.Column(db.Integer)
    usrflaganuordcom = db.Column(db.Integer)
    usrflaganugasaso = db.Column(db.Integer)
    usrflaganupagpro = db.Column(db.Integer)
    usrflaganupagdir = db.Column(db.Integer)
    usrflaganucheque = db.Column(db.Integer)
    usrflagemicobrel = db.Column(db.Integer)
    usrflagemindmor = db.Column(db.Integer)
    usrflagemindref = db.Column(db.Integer)
    usrflagemindces = db.Column(db.Integer)
    usrflagivapedido = db.Column(db.Integer)
    usrflagvencedg =    db.Column(db.Integer)
    usrflagvencegift =  db.Column(db.Integer)
    usrflagemifaccxp =  db.Column(db.Integer)
    usrflagemindcxp =   db.Column(db.Integer)
    usrflageminccxp =   db.Column(db.Integer)
    usrflagmodcredito = db.Column(db.Integer)
    usrmontolineacre =  db.Column(db.String(9))
    locestmsys =        db.Column(db.String(40))
    locaccion =         db.Column(db.String(6))
    usrflagaprproyecto =db.Column(db.Integer)
    usrflagcrucecta =   db.Column(db.Integer)
    usrflaganuproforma =db.Column(db.Integer)
    usrflagclicomenta = db.Column(db.Integer)
    usrflagclicreahis = db.Column(db.Integer)
    usrflagclielihis = db.Column(db.Integer)
    usrflagrentabilidadped = db.Column(db.Integer)
    usrflagdescuentoglobal = db.Column(db.Integer)
    usrflagvercostoinvcomp = db.Column(db.Integer)
    usrflagmodificaarticulo = db.Column(db.Integer)

class SiactlocSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Siactloc
