    
@ciacodigo,
@pednumped,
@pedsecuen,
NULL,
'PR'
,-1, 
'EFE',
'D',
0.00,   
${fechaSistema}, 
(select clicodigo from SiacIlsaboremio.dbo.facped where pednumped =@pednumped),
@loccodigo, 
1,
@pedstatus, 
'',
'01',    
@artcodigo,
'01',
'',
(select lincodigo from SiacIlsaboremio.dbo.inmart where artcodigo = @artcodigo), 
(select vencodigo from SiacIlsaboremio.dbo.facped where pednumped = @pednumped),
(select zoncodigo from SiacIlsaboremio.dbo.facped where pednumped = @pednumped),
'',
@pedcantidad,
0.000000, 
0.000000, 
(select artprecventa1 from SiacIlsaboremio.dbo.inmart where artcodigo=@artcodigo),
0.000000,
0.000000, 
0.000000, 
12.00, 
(select (artprecventa1*0.12) * @pedcantidad from SiacIlsaboremio.dbo.inmart where artcodigo=@artcodigo),
(select (artprecventa1* @pedcantidad) from SiacIlsaboremio.dbo.inmart where artcodigo=@artcodigo),
(select ((artprecventa1*0.12) + artprecventa1)*@pedcantidad from SiacIlsaboremio.dbo.inmart where artcodigo=@artcodigo),
${fechaSistema}, 
CONVERT (time, ${horaSistema}), 
@pedusuisys, 
User,
${fechaSistema}, 
CONVERT (time, ${horaSistema}), 
@pedusuisys,  
User,
'001', 
0.000000, 
'', 
0, 
0.000000, 
'UNI',
'ISM',
'0.00', 
0, 
-1, 
0,    
NULL, 
0,
'000',
'000',
${fechaSistema}, 
0.000000, 
0.000000,
10.000000,
1,
'000',
(select artdescri from SiacIlsaboremio.dbo.inmart where artcodigo=@artcodigo), 
NULL, 
NULL, 
NULL, 
NULL, 
NULL, 
NULL, 
NULL,    
NULL, 
NULL, 
NULL, 
NULL, 
NULL, 
(select mesacodigo from SiacIlsaboremio.dbo.facped where pednumped =@pednumped), 
0, 
NULL, 
@pedcomencoci,
                                                                                                                                                                                    